node/etny-node.py
=> node - code refactoring

etny-node-installer.sh
mvp-pox-node v.0.5.1
- fix home directory for root
=> changed HOME dir for ansible-playbook run

node/config.py
fixing missing packages issue (dotenv and psutil)
=> ready to test

vagrant/qemu-6.2
- fix cpu_mode https://libvirt.org/formatdomain.html#cpu-model-and-topology
=> changed cpu_mode

roles/install_node/tasks/main.yml
=> Pin vagrant-libvirt

node/utils.py
mvp-pox-node v0.5.6
- fix cache json file creation bug
=> before testing

node/.env.config, node/error_messages.py, node/etny-node.py, node/utils.py
mvp-pox-node v0.6.3
• Fixing "Transaction with the same hash has already been imported" bug
• Fixing "Transaction nonce is too low. Try incrementing the nonce." bug
• Node won't apply anymore for a transaction which has been delegated to a different node
• Fixed a smart contract interaction related to storage 
• Fixed a bug related to available RAM
=> Tranaction issues

etny-node-installer.sh, roles/install_node/tasks/debian_22.yml
mvp-pox-node v0.6.7
- fix qemu package issue
=> Pin qemu to etny version

changelog, etny-node-installer.sh, roles/validate_config_file/tasks/main.yml
mvp-pox-node v0.7.0
- added funds check for result wallet address
- fix installer logic
- remove menu option for existing config file
=> Ubuntu2004 config fix

roles/validate_config_file/tasks/main.yml
mvp-pox-node v0.7.2
- changed balance wallet check from blockexplorer.bloxberg.org to bloxberg.ethernity.cloud
=> Balancecheck

changelog, roles/install_node/tasks/debian_20.yml, roles/install_node/tasks/main.yml
mvp-pox-node v0.7.3
- fix installation issue on Ubuntu 20.04
=> Qemu fix 3

roles/install_node/tasks/main.yml
=> EPC size fix for dual CPU 

roles/install_node/tasks/main.yml
=> Apt update fix

etny-node-installer.sh, ubuntu/etny-node-isgx-removal-tool.sh, vagrant/qemu-3.1, vagrant/qemu-6.2
=> isgx removal tool 

etny-node-installer.sh, node/etny-node.py, node/utils.py, ubuntu/etny-node-isgx-removal-tool.sh, ubuntu/etny-node-provision-docker.sh, ubuntu/etny-node-provision-sgx.sh, ubuntu/etny-node-start.sh
* Upgraded task execution time to one hour
* ipfs is limited to 3GB and only up to 50 connections in the swarm
* Integration test runs for up to 5 minutes now
* Added public DNS as backup when local DNS does not resolve properly
* isgx is installed or removed based on the current mapping of the kernel driver in /dev
=> v3 changes for August

etny-node-installer.sh
=> Release V3.1

node/etny-node.py
* Changed POLYGON hearbeat frequency to 12 hours
=> Release v3.2.4

roles/validate_config_file/tasks/main.yml
Changed Mumbai RPC to: https://polygon-mumbai-pokt.nodies.app
=> Changed Mumbai RPC

roles/validate_config_file/tasks/main.yml
Changed RPC for polygon and Mumbai
=> Changed RPC for polygon and Mumbai

node/etny-node.py
Bug:
- missing "openbeta" network from etny-node.py
=> Mvp-pox-node v3.2.6

node/config.py
default RPC  fix for TESTNET and AMOY
=> Mvp-pox-node v3.2.6.2
